server {
    listen 80;
    listen [::]:80;
    server_name es.andrealkalay.com en.andrealkalay.com m.andrealkalay.com;

    include /etc/nginx/snippets/andrealkalay-legacy-redirects.conf;
    location = / { return 301 https://andrealkalay.com/; }
    location / { return 301 https://andrealkalay.com$request_uri; }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name es.andrealkalay.com en.andrealkalay.com m.andrealkalay.com;

    ssl_certificate /etc/letsencrypt/live/andrealkalay-subdomains/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/andrealkalay-subdomains/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    include /etc/nginx/snippets/andrealkalay-legacy-redirects.conf;
    location = / { return 301 https://andrealkalay.com/; }
    location / { return 301 https://andrealkalay.com$request_uri; }
}
