const entries = {
  '/about': '/acerca-de-mi',
  '/contact': '/contacto',
  '/works': '/work',
  '/gallery': '/exhibitions',
  '/galeria': '/exhibitions',

  '/unfixed': '/work/unfixed-landscapes',
  '/unfixed-landscapes': '/work/unfixed-landscapes',
  '/rockcycle': '/work/the-rock-cycle',
  '/therockcycle': '/work/the-rock-cycle',
  '/the-rock-cycle': '/work/the-rock-cycle',
  '/el-ciclo-de-la-roca': '/work/the-rock-cycle',
  '/unearth': '/work/unearth',
  '/desenterrar': '/work/unearth',
  '/landscape': '/work/landscape-on-landscape',
  '/landscapeonlandscape': '/work/landscape-on-landscape',
  '/landscapeonlandscape-1': '/work/landscape-on-landscape',
  '/landscape-on-landscape': '/work/landscape-on-landscape',
  '/kutho': '/work/kutho',
  '/briefshape': '/work/brief-shape',
  '/brief-shape': '/work/brief-shape',
  '/forma-breve': '/work/brief-shape',
  '/urbanterritories': '/work/urban-territories',
  '/urban-territories': '/work/urban-territories',
  '/territorios-urbanos': '/work/urban-territories',
  '/borders': '/work/borders',
  '/fronteras': '/work/borders',
  '/about-india': '/work/about-india',
  '/about-india-series': '/work/about-india',
  '/sobre-india': '/work/about-india',
  '/uncertain-nature': '/work/uncertain-nature-book',
  '/uncertainnature-book': '/work/uncertain-nature-book',
  '/uncertain-nature-book': '/work/uncertain-nature-book',
  '/naturaleza-incierta': '/work/uncertain-nature-book',

  '/recoleta-cultural-center': '/exhibitions/recoleta-cultural-center',
  '/copia-de-exhibitions-1': '/exhibitions/recoleta-cultural-center',
  '/espacio-dar-tucuman': '/exhibitions/espacio-dar',
  '/copia-de-recoleta-cultural-center': '/exhibitions/espacio-dar',
  '/park-pecno-slovenia': '/exhibitions/park-pecno-slovenia',
  '/copia-de-exhibitions': '/exhibitions/park-pecno-slovenia',
  '/museo-bellas-artes-frankling-rawson': '/exhibitions/museo-franklin-rawson',
  '/museofranklingrawson': '/exhibitions/museo-franklin-rawson',
  '/oda-arte-art-fairs': '/exhibitions/art-fairs',
  '/copia-de-oda-arte-art-fairs': '/exhibitions/art-fairs',
  '/mundo-nuevo-gallery-art': '/exhibitions/mundo-nuevo-gallery',
  '/mundonuevogalleryart': '/exhibitions/mundo-nuevo-gallery',
  '/centroculturalmapocho': '/exhibitions/estacion-mapocho-chile',
  '/centro-cultural-mapocho-chile': '/exhibitions/estacion-mapocho-chile',
  '/mundo-nuevo-kutho': '/work/kutho',
  '/mundo-nuevo-kutho-group-show': '/work/kutho'
};

export const LEGACY_REDIRECTS = Object.freeze(entries);

export const legacyDestination = pathname => LEGACY_REDIRECTS[String(pathname || '').toLowerCase()] || null;
